// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5r_NSDnFcfRq-BNw3ei969EnKQ2RUc04',
    appId: '1:396406873253:web:c613fcea951df74f06414c',
    messagingSenderId: '396406873253',
    projectId: 'safestride-ed8a1',
    authDomain: 'safestride-ed8a1.firebaseapp.com',
    storageBucket: 'safestride-ed8a1.firebasestorage.app',
    measurementId: 'G-9BQJ9SDXDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAquo9JufUz5UD9gC7W9Ah-eM21RTTaCZs',
    appId: '1:396406873253:android:433506d665e6828b06414c',
    messagingSenderId: '396406873253',
    projectId: 'safestride-ed8a1',
    storageBucket: 'safestride-ed8a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfSAeW_Q9Tr7ouOLt_UCxtIfsUL51qDjc',
    appId: '1:396406873253:ios:af717fd0e29734e306414c',
    messagingSenderId: '396406873253',
    projectId: 'safestride-ed8a1',
    storageBucket: 'safestride-ed8a1.firebasestorage.app',
    iosBundleId: 'com.example.flutterFundamentals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfSAeW_Q9Tr7ouOLt_UCxtIfsUL51qDjc',
    appId: '1:396406873253:ios:af717fd0e29734e306414c',
    messagingSenderId: '396406873253',
    projectId: 'safestride-ed8a1',
    storageBucket: 'safestride-ed8a1.firebasestorage.app',
    iosBundleId: 'com.example.flutterFundamentals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5r_NSDnFcfRq-BNw3ei969EnKQ2RUc04',
    appId: '1:396406873253:web:bfc684877fb8221106414c',
    messagingSenderId: '396406873253',
    projectId: 'safestride-ed8a1',
    authDomain: 'safestride-ed8a1.firebaseapp.com',
    storageBucket: 'safestride-ed8a1.firebasestorage.app',
    measurementId: 'G-FSKG7MTESK',
  );
}
