import '../models/route_model.dart';

class MockData {
  static final List<RouteModel> routes = [
    RouteModel(
      id: 1,
      name: 'Riverside Trail',
      category: 'Runner',
      distance: '5.2 km',
      safety: 95,
      lighting: 'Excellent',
      traffic: 'Low',
      crowd: 'Moderate',
      reviews: 128,
      rating: 4.8,
      image: 'nature running trail',
      emoji: '🏃‍♂️',
    ),
    RouteModel(
      id: 2,
      name: 'Downtown Circuit',
      category: 'Cyclist',
      distance: '12.8 km',
      safety: 78,
      lighting: 'Good',
      traffic: 'Moderate',
      crowd: 'High',
      reviews: 89,
      rating: 4.5,
      image: 'urban cycling path',
      emoji: '🚴‍♀️',
    ),
    RouteModel(
      id: 3,
      name: 'Mountain View Loop',
      category: 'Runner',
      distance: '8.4 km',
      safety: 88,
      lighting: 'Moderate',
      traffic: 'Very Low',
      crowd: 'Low',
      reviews: 215,
      rating: 4.9,
      image: 'mountain trail running',
      emoji: '🏃‍♀️',
    ),
  ];

  static final List<RouteModel> featuredRoutes = [
    RouteModel(
      id: 1,
      name: 'Coastal Sunrise Path',
      distance: '6.8 km',
      safety: 92,
      category: 'Runner',
      rating: 4.9,
      reviews: 156,
      image: 'coastal path sunrise running',
      tag: 'Trending',
      emoji: '🏃‍♀️',
      lighting: 'Excellent',
      traffic: 'Low',
      crowd: 'Moderate',
    ),
    RouteModel(
      id: 2,
      name: 'Forest Loop Adventure',
      distance: '15.2 km',
      safety: 85,
      category: 'Cyclist',
      rating: 4.7,
      reviews: 203,
      image: 'forest cycling trail',
      tag: 'Popular',
      emoji: '🚴‍♂️',
      lighting: 'Good',
      traffic: 'Moderate',
      crowd: 'Low',
    ),
    RouteModel(
      id: 3,
      name: 'Urban Park Circuit',
      distance: '4.5 km',
      safety: 95,
      category: 'Runner',
      rating: 4.8,
      reviews: 312,
      image: 'urban park running',
      tag: 'Safe',
      emoji: '🏃',
      lighting: 'Excellent',
      traffic: 'Very Low',
      crowd: 'Moderate',
    ),
  ];

  static final List<Review> reviews = [
    Review(
      id: 1,
      author: 'Sarah Chen',
      avatar: 'woman portrait professional',
      rating: 5,
      date: 'Feb 14, 2026',
      text: 'Perfect morning run route! Well-lit and very safe. The riverside views are absolutely stunning.',
      helpful: 24,
    ),
    Review(
      id: 2,
      author: 'Marcus Johnson',
      avatar: 'man portrait professional',
      rating: 5,
      date: 'Feb 12, 2026',
      text: 'Great for cycling. Smooth path with minimal traffic. Highly recommended for early morning rides.',
      helpful: 18,
    ),
    Review(
      id: 3,
      author: 'Emily Rodriguez',
      avatar: 'woman runner portrait',
      rating: 4,
      date: 'Feb 10, 2026',
      text: 'Love this trail! Only minor issue is it can get crowded on weekends. Go early for best experience.',
      helpful: 15,
    ),
  ];

  static final List<AlertModel> alerts = [
    AlertModel(
      id: 1,
      type: 'warning',
      title: 'Route Closure Alert',
      message: 'Riverside Trail section temporarily closed due to maintenance.',
      location: 'Riverside Trail',
      time: '2 hours ago',
      color: '#fbbf24',
    ),
    AlertModel(
      id: 2,
      type: 'success',
      title: 'New Route Added',
      message: 'Check out the newly discovered "Sunset Boulevard Loop" - 95% safety rating!',
      location: 'Downtown Area',
      time: '5 hours ago',
      color: '#7df258',
    ),
    AlertModel(
      id: 3,
      type: 'info',
      title: 'Improved Lighting',
      message: 'Mountain View Loop now has enhanced lighting. Updated safety score: 92%',
      location: 'Mountain View Loop',
      time: '1 day ago',
      color: '#3b82f6',
    ),
    AlertModel(
      id: 4,
      type: 'warning',
      title: 'Heavy Traffic Warning',
      message: 'Downtown Circuit experiencing higher than usual traffic. Consider alternative routes.',
      location: 'Downtown Circuit',
      time: '2 days ago',
      color: '#fbbf24',
    ),
  ];
}
